CREATE DATABASE IF NOT EXISTS tp2_tareas
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE tp2_tareas;

CREATE TABLE IF NOT EXISTS tareas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) COLLATE utf8mb4_0900_ai_ci NOT NULL,
  completada BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uq_tareas_nombre UNIQUE (nombre)
);